name: Python codeqa/test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-lint
    - name: Install dependencies
      run: pip install flake8 isort mypy
    - name: Run flake8
      run: flake8 apscheduler tests
#    - name: Check types with Mypy
#      run: mypy apscheduler
    - name: Run isort
      run: isort -c apscheduler tests

  test-linux:
    needs: [lint]
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.9.2]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install the project and its dependencies
      run: pip install -e .[test,cbor,postgresql,mongodb]
    - name: Start external services
      run: docker-compose up -d
    - name: Test with pytest
      run: pytest tests/test_marshalling.py

  test-others:
    needs: [lint]
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.7, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install the project and its dependencies
      run: pip install -e .[test,cbor]
    - name: Test with pytest
      run: pytest tests/test_marshalling.py
